services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      - DJANGO_SETTINGS_MODULE=moviedb.settings.prod
    command: "/app/entrypoint.sh"
