# Generated by Django 3.1.4 on 2020-12-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_watched',
            field=models.DateField(blank=True, null=True),
        ),
    ]
