# Generated by Django 3.1.1 on 2021-06-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
